name: Build & Release (Dev)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: flutter-${{ hashFiles('**/.flutter-plugins') }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --flavor dev --target main_dev.dart | tee build_log.txt

      - name: Build App Bundle
        run: flutter build appbundle --flavor dev --target main_dev.dart

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-release
        path: |
          build/app/outputs/apk/release/
          build/app/outputs/bundle/release/
